name: Run myproject_2.cpp

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt update && sudo apt install -y g++

      - name: Compile myproject_2.cpp
        run: g++ -o myproject_2 myproject_2.cpp

      - name: Run myproject_2
        run: ./myproject_2
